Add interchain account queries
AbstractSDK/abstract.js pull request #50
Opened 2024-01-31 00:31 UTC by adairrr

Adds queries for retrieving remote account ids and remote proxies.

<[APP-269 : Add ICAA Proxy Queries to Abstract.js](https://linear.app/abstract-sdk/issue/APP-269/add-icaa-proxy-queries-to-abstractjs)>

2024-01-31 16:09 UTC, dalechyn requested changes
awesome! one comment tho.

2024-01-31 16:09 UTC, dalechyn commented on packages/core/src/actions/account/public/get-ibc-client-query-client-from-manager.ts
> +const IBC_CLIENT_MODULE_ID = 'abstract:ibc-client'
interesting, `vanilla` plugin could have done it instead, but it doesn't.

2024-01-31 16:09 UTC, dalechyn commented on packages/core/src/actions/account/public/get-remote-account-proxies.ts
> +  }
I think it's okay to throw an error here.

2024-01-31 16:20 UTC, adairrr commented on packages/core/src/actions/account/public/get-remote-account-proxies.ts
> +  }
Thought so too initially but devx-wise it's nicer to get "no proxies" because they can check whether ibc is enabled via the manager.

2024-01-31 17:13 UTC, dalechyn requested changes
alles good, please run `pnpm changeset` from the root of the repo, write a changeset and I'll hit that approve button!

2024-02-01 20:09 UTC, dalechyn approved these changes

2024-02-02 06:43 UTC, merged